-- PostgreSQL version
-- Create the database manually if needed:
-- CREATE DATABASE opt_db;
-- Then connect to it:
-- \c opt_db

DROP TABLE IF EXISTS opt_orders;
DROP TABLE IF EXISTS opt_products;
DROP TABLE IF EXISTS opt_clients;

CREATE TABLE IF NOT EXISTS opt_clients (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS opt_products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_category VARCHAR(50) NOT NULL CHECK (
        product_category IN ('Category1', 'Category2', 'Category3', 'Category4', 'Category5')
    ),
    description TEXT
);

CREATE TABLE IF NOT EXISTS opt_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    client_id UUID,
    product_id INTEGER,
    CONSTRAINT fk_opt_orders_client
        FOREIGN KEY (client_id) REFERENCES opt_clients(id),
    CONSTRAINT fk_opt_orders_product
        FOREIGN KEY (product_id) REFERENCES opt_products(product_id)
);


DROP INDEX IF EXISTS idx_opt_orders_order_date;
DROP INDEX IF EXISTS idx_opt_orders_client_id;
DROP INDEX IF EXISTS idx_opt_clients_status;

EXPLAIN ANALYZE
SELECT
    (
        SELECT CONCAT('Client ID ', client_id, ' (Замовлень: ', cnt, ')')
        FROM (
            SELECT c.id AS client_id, COUNT(*) AS cnt
            FROM opt_orders AS o
            JOIN opt_clients AS c ON o.client_id = c.id
            WHERE o.order_date > DATE '2023-01-01'
              AND c.status = 'active'
            GROUP BY c.id
        ) AS sub1
        WHERE cnt = (
            SELECT MIN(cnt)
            FROM (
                SELECT COUNT(*) AS cnt
                FROM opt_orders AS o
                JOIN opt_clients AS c ON o.client_id = c.id
                WHERE o.order_date > DATE '2023-01-01'
                  AND c.status = 'active'
                GROUP BY c.id
            ) AS sub3
        )
        LIMIT 1
    ) AS least_active_client,

    (
        SELECT CONCAT('Client ID ', client_id, ' (Замовлень: ', cnt, ')')
        FROM (
            SELECT c.id AS client_id, COUNT(*) AS cnt
            FROM opt_orders AS o
            JOIN opt_clients AS c ON o.client_id = c.id
            WHERE o.order_date > DATE '2023-01-01'
              AND c.status = 'active'
            GROUP BY c.id
        ) AS sub2
        WHERE cnt = (
            SELECT MAX(cnt)
            FROM (
                SELECT COUNT(*) AS cnt
                FROM opt_orders AS o
                JOIN opt_clients AS c ON o.client_id = c.id
                WHERE o.order_date > DATE '2023-01-01'
                  AND c.status = 'active'
                GROUP BY c.id
            ) AS sub4
        )
        LIMIT 1
    ) AS most_active_client; -- execution time:2451.331ms(неоптимізова кверя)


CREATE INDEX IF NOT EXISTS idx_opt_orders_order_date
    ON opt_orders(order_date);

CREATE INDEX IF NOT EXISTS idx_opt_orders_client_id
    ON opt_orders(client_id);

CREATE INDEX IF NOT EXISTS idx_opt_clients_status
    ON opt_clients(status);

EXPLAIN ANALYZE
WITH client_counts AS (
    SELECT
        c.id AS client_id,
        COUNT(o.order_id) AS cnt
    FROM opt_orders AS o
    JOIN opt_clients AS c
        ON o.client_id = c.id
    WHERE o.order_date > DATE '2023-01-01'
      AND c.status = 'active'
    GROUP BY c.id
),
ranked_clients AS (
    SELECT
        client_id,
        cnt,
        ROW_NUMBER() OVER (ORDER BY cnt, client_id) AS min_rn,
        ROW_NUMBER() OVER (ORDER BY cnt DESC, client_id ) AS max_rn
    FROM client_counts
)
SELECT
    MAX(CONCAT('Client ID ', client_id, ' (Замовлень: ', cnt, ')')) FILTER (WHERE min_rn = 1) AS least_active_client,
    MAX(CONCAT('Client ID ', client_id, ' (Замовлень: ', cnt, ')')) FILTER (WHERE max_rn = 1) AS most_active_client
FROM ranked_clients; -- execution time: 1051.945 ms(оптимізована кверя,+ не врахочуючи час на створення індексів)